### ISSUE TITLE
page crash when hover on auto-verified ens address

### ISSUE THREAD

**Issue by iampkuhz** [blockscout/frontend#2188]
### Description

When I move cursor on Address ENS name, the page crashed. It happened only when the to address is verified automatically in contract page. If the page is not verifed and only show orignal `0x***` format address, the hover won't cause this bug. However, this always happened after auto verified, no matter which page. transaction list page, contract list page, both of them would have such bug.

at the very begining, we're using `v1.33.0`. After upgrade to `v1.33.2`, this problem still occured.

> hover here will cause 500 error. noted that we haven't have a chance to click it.
> ![43DD5642-12B5-454F-9A7B-FDDCA2D20437](https://github.com/user-attachments/assets/2f9f0b98-93a0-4601-875b-94440bd5366c)

there is a exception in console:
```
TypeError: Cannot read properties of undefined (reading 'length')
    at HashStringShortenDynamic.tsx:94:28
    at ak (react-dom.production.min.js:167:135)
    at up (react-dom.production.min.js:197:256)
    at uc (react-dom.production.min.js:195:197)
    at us (react-dom.production.min.js:194:50)
    at i (react-dom.production.min.js:297:9)
    at oD (react-dom.production.min.js:280:383)
    at react-dom.production.min.js:280:319
    at oO (react-dom.production.min.js:280:319)
    at oE (react-dom.production.min.js:271:86)
```
![20240823113345](https://github.com/user-attachments/assets/088d51e9-df6a-43ba-8815-46fea82b1abd)

### Link to the page

local deployed network

### Steps to reproduce

1. Go to main page
2. Click on a random txn which to address is a contract
3. switch to `contract` tab in contract page and try to trigger sc verifier service to auto verify this contract
4. go back to main page and this time the to address will be replaced by `ERC1967Proxy` ENS
5. hover on `ERC1967Proxy` and the crash happened

### App version

v1.33.2

### Operating system

macOS

**Comment by iampkuhz** [comment]
@yvaskov Backend: [v6.6.0-beta](https://github.com/blockscout/blockscout/tree/v6.6.0-beta)

**Comment by yvaskov** [comment]
@iampkuhz this version is missing some of the proxy implementation preloads. I suggest upgrading to the latest version, as it has been fixed.

**Comment by iampkuhz** [comment]
@yvaskov change the front-end to the latest version but the problem still occurred 
![image](https://github.com/user-attachments/assets/b5610a14-05f3-4019-b01c-d8a3a81cdaf1)

**Comment by yvaskov** [comment]
@iampkuhz I meant the backend version

**Comment by iampkuhz** [comment]
after upgraded the backend version, this bug was fixed.
